version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run build

artifacts:
  files:
    - "**/*"
