
AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EC2 instance running PBS-HLL-Discord-Bot
Resources:
  ElasticBeanstalkApplication:
    Type: "AWS::ElasticBeanstalk::Application"
    Properties:
      ApplicationName: "PBS-HLL-Discord-Bot-App"
  ElasticBeanstalkEnvironment:
    Type: "AWS::ElasticBeanstalk::Environment"
    Properties:
      # DISCORD_BOT_TOKEN env variable is set manually on the EB dashboard
      EnvironmentName: "PBS-HLL-Discord-Bot-Env"
      ApplicationName: !Ref ElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2 v5.2.1 running Node.js 12"
      OptionSettings:
        - Namespace:  aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.nano
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: aws-elasticbeanstalk-service-role
