
AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EC2 instance running PBS-HLL-Discord-Bot
Resources:
  ElasticBeanstalkApplication:
    Type: "AWS::ElasticBeanstalk::Application"
    Properties:
      ApplicationName: "PBS-HLL-Discord-Bot-App"
  ElasticBeanstalkConfiguration:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      OptionSettings:
        - Namespace:  aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
  ElasticBeanstalkEnvironment:
    Type: "AWS::ElasticBeanstalk::Environment"
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2 v5.2.1 running Node.js 12"
  